<?php /* Smarty version 2.6.9, created on 2007-11-17 01:37:29
         compiled from /var/www/knowledgeTree/templates/kt3/fields/fileupload.smarty */

$this->_cache_serials['/var/www/knowledgeTree/var/tmp/%%3C^3C8^3C80D8B3%%fileupload.smarty.inc'] = '0f025c316e28d0d701f221bb14d1a3b1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'i18n', '/var/www/knowledgeTree/templates/kt3/fields/fileupload.smarty', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_0f025c316e28d0d701f221bb14d1a3b1_0(&$this)
{
$this->_tag_stack[] = array('i18n', array()); KTSmartyTemplate::i18n_block($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat=true);while ($_block_repeat) { ob_start(); ?>Required<?php $_block_content = ob_get_contents(); ob_end_clean(); echo KTSmartyTemplate::i18n_block($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat=false); }  array_pop($this->_tag_stack); 
}



?>
